PSO769PI ;BHAM/MFR - PSO*7*746 POST INSTALL; 10/01/2022 11:24Am
 ;;7.0;OUTPATIENT PHARMACY;**769**;DEC 1997;Build 26
 ;
EN       ; Entry Point
 N XMDUZ,XMSUB,XMY,PSOTEXT,DIFROM
 ; Production Account check only
 I '$$PROD^XUPROD() Q
 I $D(^TIU(8925.1,"B","ERX RX CHANGE REQUEST NOTE")) Q
 ;
 S XMDUZ="Patch PSO*7*769",XMSUB="ERX RX CHANGE REQUEST NOTE TIU TITLE NOT FOUND"
 S XMY("MIAN.NAEEM@DOMAIN.EXT")=""
 S XMY("BAYLIS.RANDALL@FORUM.VA.GO")=""
 S XMY("ROCHA.MARCELO@DOMAIN.EXT")=""
 S XMY("MURPHY.ROSALIE@DOMAIN.EXT")=""
 S XMY("CHU.ANN@DOMAIN.EXT")=""
 S PSOTEXT(1)="Site "_$P($$SITE^VASITE(),"^",2)_" does not have the ERX CHANGE REQUEST TIU TITLE."
 S PSOTEXT(2)=" "
 S XMTEXT="PSOTEXT("
 D ^XMD
 ;
 Q
